### ISSUE TITLE
Expose decisecond or better precision

### ISSUE THREAD

**Issue by curby** [NodeGuy/ServerDate#17]
Update interval and display precision should be selectable.  E.g. update every decisecond, with decisecond or centisecond precision.  Update every centisecond, with centisecond or millisecond precision.  I understand that the accuracy may not be sufficient in all cases, and that higher update frequency will tax client resources, but this should at least be an option since ServerDate can generally produce better-than-second accuracy.

This may already be possible with the current code, but it is not exposed in example.html.

**Comment by curby** [comment]
This modification of example.html displays centiseconds with default ServerDate javascript/php.  CPU activity does jump up, but it seems to keep up pretty well. 

http://ntp2.curby.net/example-centiseconds.html

**Comment by NodeGuy** [comment]
Synchronization frequency is already selectable via `ServerDate.synchronizationIntervalDelay`.

The example is designed to be simple and modifiable as desired by the end user, not to satisfy all use cases.
