### ISSUE TITLE
getTimezoneOffset throws exception

### ISSUE THREAD

**Issue by curby** [NodeGuy/ServerDate#19]
Adding this to the end of the last `<script>` element in example.html:

`alert(ServerDate.getTimezoneOffest());`

throws this in Chrome's Console:

`Uncaught TypeError: undefined is not a function`

This might not be considered a problem in ServerDate as it just does what Date would do.

**Comment by NodeGuy** [comment]
Looks like you have a typo: `Offest` should be `Offset`.

**Comment by curby** [comment]
Ha, I'm dumb.  Sorry about that.
