### ISSUE TITLE
Browser caching causes incorrect ServerDate initialization

### ISSUE THREAD

**Issue by curby** [NodeGuy/ServerDate#21]
The PHP script appends the current timestamp and sends it to the client as part of the javascript request

<script src="ServerDate.php"></script>

and the resulting script is cached by the browser along with its initializing epoch timestamp.

If you navigate away from the page that loaded ServerDate and then later revisit by hitting the back button, the cached script (with now-obsolete timestamp) is used to initialize the clock.

This skews the initial target as well as the offset of the first sample retrieved from the server during the first synchronization of the newly-reloaded ServerDate object.

**Comment by NodeGuy** [comment]
Fixed in 16d946b4a04a3a264cffeb23df9dd17e4c78ee03.
