### ISSUE TITLE
not accurate at all

### ISSUE THREAD

**Issue by greg606** [NodeGuy/ServerDate#24]
i need to sync clients. but your functions shows two different times (1s diff) in two browsers (on one computer) 
unless i do something wrong and then maybe you could correct me. i have seconds based sessions and 1s difference is huge.
I would be grateful for any advice how to make timers accurate (each start at the same server time )

```
Game.toFullSecond = 1000 - ServerDate.getMilliseconds();
        setTimeout(function () {
            timer = new CountDownTimer(seconds);
        }, Game.toFullSecond);

**Comment by NodeGuy** [comment]
Try looking at the messages in the JavaScript console of each browser for more information about what's going on.
