### ISSUE TITLE
ServerDate on CDN

### ISSUE THREAD

**Issue by glowworms** [NodeGuy/ServerDate#34]
Please consider submitting ServerDate to cdnjs.com
They will host the script for free.

**Comment by NodeGuy** [comment]
Good idea.  Why'd you close the issue?

**Comment by glowworms** [comment]
Thanks. That would be great.

You can Request it here by submitting an issue: https://github.com/cdnjs/cdnjs/issues

**Comment by NodeGuy** [comment]
So let me understand this better:  You want to synchronize the browser clock with the clock of one of CDNJS's servers?

**Comment by glowworms** [comment]
hmm... I don't know what that would produce.
Would the CDNJS servers be in random timezones?

**Comment by NodeGuy** [comment]
I have no idea.  I don't think this is what you want—ServerDate is for synchronizing the browser with a specific server that's hosting the script.

**Comment by glowworms** [comment]
Could you release a Dev version and get cloudflare to host it to try to see if we could make this work the way we want?
Or create fork of ServerDate and modify it to work hosted from a cloudflare?

I could try to help you with this.

**Comment by NodeGuy** [comment]
I'm open to it but I'd like to hear more about your use case first.  What are you trying to accomplish?

**Comment by sreekotay** [comment]
If you have ServerDate.js hosted on a CDN, no one has to deploy it to/on their server (if the goal is to sync multiple clients, for example).

**Comment by NodeGuy** [comment]
Right, but I don't think that's going to work well because the CDN will be serving from multiple servers.

Regardless, CDNJS [requires popularity of at least 200 stars](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for submission.  I'm closing this issue for now but we can re-open in the future if it makes sense.
