### ISSUE TITLE
not an "issue", but fyi

### ISSUE THREAD

**Issue by jonathan-annett** [NodeGuy/ServerDate#37]
I beefed up ServerDate a bit to handle websockets and/or socket.io

(note i spun off the server ping functionality into serverPing.js which handles the ws/socket.io/xhr mode selection based on what it can get away with)

working glich here

https://separate-brisket.glitch.me/

code here:

https://glitch.com/~separate-brisket

**Comment by NodeGuy** [comment]
Nice!  Thanks for sharing.
